<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{

    public function run()
    {
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'receitas_iptu_menu',
            'receitas_iptu_index',
            'receitas_iptu_create',
            'receitas_iptu_show',
            'receitas_iptu_read',
            'receitas_iptu_store',
            'receitas_iptu_edit',
            'receitas_iptu_update',
            'receitas_iptu_destroy',
            'receitas_iptu_delete',

            'receitas_iss_menu',
            'receitas_iss_index',
            'receitas_iss_create',
            'receitas_iss_show',
            'receitas_iss_read',
            'receitas_iss_store',
            'receitas_iss_edit',
            'receitas_iss_update',
            'receitas_iss_destroy',
            'receitas_iss_delete',

            'receitas_divida_ativa_menu',
            'receitas_divida_ativa_index',
            'receitas_divida_ativa_create',
            'receitas_divida_ativa_show',
            'receitas_divida_ativa_read',
            'receitas_divida_ativa_store',
            'receitas_divida_ativa_edit',
            'receitas_divida_ativa_update',
            'receitas_divida_ativa_destroy',
            'receitas_divida_ativa_delete',

            'fiscal_ipm_menu',
            'fiscal_ipm_index',
            'fiscal_ipm_create',
            'fiscal_ipm_show',
            'fiscal_ipm_read',
            'fiscal_ipm_store',
            'fiscal_ipm_edit',
            'fiscal_ipm_update',
            'fiscal_ipm_destroy',
            'fiscal_ipm_delete',

            'painel_acoes_projetos_menu',
            'painel_acoes_projetos_index',
            'painel_acoes_projetos_create',
            'painel_acoes_projetos_show',
            'painel_acoes_projetos_read',
            'painel_acoes_projetos_store',
            'painel_acoes_projetos_edit',
            'painel_acoes_projetos_update',
            'painel_acoes_projetos_destroy',
            'painel_acoes_projetos_delete',

            'agendamento_agenda_menu',
            'agendamento_agenda_index',
            'agendamento_agenda_create',
            'agendamento_agenda_show',
            'agendamento_agenda_read',
            'agendamento_agenda_store',
            'agendamento_agenda_edit',
            'agendamento_agenda_update',
            'agendamento_agenda_destroy',
            'agendamento_agenda_delete',

            'agendamento_config_menu',
            'agendamento_config_index',
            'agendamento_config_create',
            'agendamento_config_show',
            'agendamento_config_read',
            'agendamento_config_store',
            'agendamento_config_edit',
            'agendamento_config_update',
            'agendamento_config_destroy',
            'agendamento_config_delete',

            'agendamento_config_atendimento_menu',
            'agendamento_config_atendimento_index',
            'agendamento_config_atendimento_create',
            'agendamento_config_atendimento_show',
            'agendamento_config_atendimento_read',
            'agendamento_config_atendimento_store',
            'agendamento_config_atendimento_edit',
            'agendamento_config_atendimento_update',
            'agendamento_config_atendimento_destroy',
            'agendamento_config_atendimento_delete',

            'agendamento_config_feriado_menu',
            'agendamento_config_feriado_index',
            'agendamento_config_feriado_create',
            'agendamento_config_feriado_show',
            'agendamento_config_feriado_read',
            'agendamento_config_feriado_store',
            'agendamento_config_feriado_edit',
            'agendamento_config_feriado_update',
            'agendamento_config_feriado_destroy',
            'agendamento_config_feriado_delete',

            'account_settings_menu',
            'account_settings_index',
            'account_settings_create',
            'account_settings_show',
            'account_settings_read',
            'account_settings_store',
            'account_settings_edit',
            'account_settings_update',
            'account_settings_destroy',
            'account_settings_delete',

            'account_settings_users_menu',
            'account_settings_users_index',
            'account_settings_users_create',
            'account_settings_users_show',
            'account_settings_users_read',
            'account_settings_users_store',
            'account_settings_users_edit',
            'account_settings_users_update',
            'account_settings_users_destroy',
            'account_settings_users_delete',

            'account_settings_access_group_menu',
            'account_settings_access_group_index',
            'account_settings_access_group_create',
            'account_settings_access_group_show',
            'account_settings_access_group_read',
            'account_settings_access_group_store',
            'account_settings_access_group_edit',
            'account_settings_access_group_update',
            'account_settings_access_group_destroy',
            'account_settings_access_group_delete',

            'account_settings_users_permission_menu',
            'account_settings_users_permission_index',
            'account_settings_users_permission_create',
            'account_settings_users_permission_show',
            'account_settings_users_permission_read',
            'account_settings_users_permission_store',
            'account_settings_users_permission_edit',
            'account_settings_users_permission_update',
            'account_settings_users_permission_destroy',
            'account_settings_users_permission_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',

        ] as $name) {
            Permission::create(['name' => $name])->roles()->attach(1);
        }

        $role2 = Role::findById(2);
        $role3 = Role::findById(3);
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'receitas_iptu_menu',
            'receitas_iptu_index',
            'receitas_iptu_create',
            'receitas_iptu_show',
            'receitas_iptu_read',
            'receitas_iptu_store',
            'receitas_iptu_edit',
            'receitas_iptu_update',
            'receitas_iptu_destroy',
            'receitas_iptu_delete',

            'receitas_iss_menu',
            'receitas_iss_index',
            'receitas_iss_create',
            'receitas_iss_show',
            'receitas_iss_read',
            'receitas_iss_store',
            'receitas_iss_edit',
            'receitas_iss_update',
            'receitas_iss_destroy',
            'receitas_iss_delete',

            'receitas_divida_ativa_menu',
            'receitas_divida_ativa_index',
            'receitas_divida_ativa_create',
            'receitas_divida_ativa_show',
            'receitas_divida_ativa_read',
            'receitas_divida_ativa_store',
            'receitas_divida_ativa_edit',
            'receitas_divida_ativa_update',
            'receitas_divida_ativa_destroy',
            'receitas_divida_ativa_delete',

            'fiscal_ipm_menu',
            'fiscal_ipm_index',
            'fiscal_ipm_create',
            'fiscal_ipm_show',
            'fiscal_ipm_read',
            'fiscal_ipm_store',
            'fiscal_ipm_edit',
            'fiscal_ipm_update',
            'fiscal_ipm_destroy',
            'fiscal_ipm_delete',

            'painel_acoes_projetos_menu',
            'painel_acoes_projetos_index',
            'painel_acoes_projetos_create',
            'painel_acoes_projetos_show',
            'painel_acoes_projetos_read',
            'painel_acoes_projetos_store',
            'painel_acoes_projetos_edit',
            'painel_acoes_projetos_update',
            'painel_acoes_projetos_destroy',
            'painel_acoes_projetos_delete',

            'agendamento_agenda_menu',
            'agendamento_agenda_index',
            'agendamento_agenda_create',
            'agendamento_agenda_show',
            'agendamento_agenda_read',
            'agendamento_agenda_store',
            'agendamento_agenda_edit',
            'agendamento_agenda_update',
            'agendamento_agenda_destroy',
            'agendamento_agenda_delete',

            'agendamento_config_menu',
            'agendamento_config_index',
            'agendamento_config_create',
            'agendamento_config_show',
            'agendamento_config_read',
            'agendamento_config_store',
            'agendamento_config_edit',
            'agendamento_config_update',
            'agendamento_config_destroy',
            'agendamento_config_delete',

            'agendamento_config_atendimento_menu',
            'agendamento_config_atendimento_index',
            'agendamento_config_atendimento_create',
            'agendamento_config_atendimento_show',
            'agendamento_config_atendimento_read',
            'agendamento_config_atendimento_store',
            'agendamento_config_atendimento_edit',
            'agendamento_config_atendimento_update',
            'agendamento_config_atendimento_destroy',
            'agendamento_config_atendimento_delete',

            'agendamento_config_feriado_menu',
            'agendamento_config_feriado_index',
            'agendamento_config_feriado_create',
            'agendamento_config_feriado_show',
            'agendamento_config_feriado_read',
            'agendamento_config_feriado_store',
            'agendamento_config_feriado_edit',
            'agendamento_config_feriado_update',
            'agendamento_config_feriado_destroy',
            'agendamento_config_feriado_delete',

            'account_settings_menu',
            'account_settings_index',
            'account_settings_create',
            'account_settings_show',
            'account_settings_read',
            'account_settings_store',
            'account_settings_edit',
            'account_settings_update',
            'account_settings_destroy',
            'account_settings_delete',

            'account_settings_users_menu',
            'account_settings_users_index',
            'account_settings_users_create',
            'account_settings_users_show',
            'account_settings_users_read',
            'account_settings_users_store',
            'account_settings_users_edit',
            'account_settings_users_update',
            'account_settings_users_destroy',
            'account_settings_users_delete',

            'account_settings_access_group_menu',
            'account_settings_access_group_index',
            'account_settings_access_group_create',
            'account_settings_access_group_show',
            'account_settings_access_group_read',
            'account_settings_access_group_store',
            'account_settings_access_group_edit',
            'account_settings_access_group_update',
            'account_settings_access_group_destroy',
            'account_settings_access_group_delete',

            'account_settings_users_permission_menu',
            'account_settings_users_permission_index',
            'account_settings_users_permission_create',
            'account_settings_users_permission_show',
            'account_settings_users_permission_read',
            'account_settings_users_permission_store',
            'account_settings_users_permission_edit',
            'account_settings_users_permission_update',
            'account_settings_users_permission_destroy',
            'account_settings_users_permission_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',
        ] as $name) {
            $permission2 = Permission::where('name', $name)->first();
            $role2->givePermissionTo($permission2);
            $role3->givePermissionTo($permission2);
        }

        $role4 = Role::findById(4);
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'receitas_divida_ativa_menu',
            'receitas_divida_ativa_index',
            'receitas_divida_ativa_create',
            'receitas_divida_ativa_show',
            'receitas_divida_ativa_read',
            'receitas_divida_ativa_store',
            'receitas_divida_ativa_edit',
            'receitas_divida_ativa_update',
            'receitas_divida_ativa_destroy',
            'receitas_divida_ativa_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',



        ] as $name) {
            $permission4 = Permission::where('name', $name)->first();
            $role4->givePermissionTo($permission4);
        }

        $role5 = Role::findById(5);
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'receitas_iss_menu',
            'receitas_iss_index',
            'receitas_iss_create',
            'receitas_iss_show',
            'receitas_iss_read',
            'receitas_iss_store',
            'receitas_iss_edit',
            'receitas_iss_update',
            'receitas_iss_destroy',
            'receitas_iss_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',



        ] as $name) {
            $permission5 = Permission::where('name', $name)->first();
            $role5->givePermissionTo($permission5);
        }

        $role6 = Role::findById(6);
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'receitas_iptu_menu',
            'receitas_iptu_index',
            'receitas_iptu_create',
            'receitas_iptu_show',
            'receitas_iptu_read',
            'receitas_iptu_store',
            'receitas_iptu_edit',
            'receitas_iptu_update',
            'receitas_iptu_destroy',
            'receitas_iptu_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',



        ] as $name) {
            $permission6 = Permission::where('name', $name)->first();
            $role6->givePermissionTo($permission6);
        }

        $role7 = Role::findById(7);
        foreach ([
            'dashboard_menu',
            'dashboard_index',
            'dashboard_create',
            'dashboard_show',
            'dashboard_read',
            'dashboard_store',
            'dashboard_edit',
            'dashboard_update',
            'dashboard_destroy',
            'dashboard_delete',

            'fiscal_ipm_menu',
            'fiscal_ipm_index',
            'fiscal_ipm_create',
            'fiscal_ipm_show',
            'fiscal_ipm_read',
            'fiscal_ipm_store',
            'fiscal_ipm_edit',
            'fiscal_ipm_update',
            'fiscal_ipm_destroy',
            'fiscal_ipm_delete',

            'agendamento_agenda_menu',
            'agendamento_agenda_index',
            'agendamento_agenda_create',
            'agendamento_agenda_show',
            'agendamento_agenda_read',
            'agendamento_agenda_store',
            'agendamento_agenda_edit',
            'agendamento_agenda_update',
            'agendamento_agenda_destroy',
            'agendamento_agenda_delete',

            'account_settings_users_profile_menu',
            'account_settings_users_profile_index',
            'account_settings_users_profile_create',
            'account_settings_users_profile_show',
            'account_settings_users_profile_read',
            'account_settings_users_profile_store',
            'account_settings_users_profile_edit',
            'account_settings_users_profile_update',
            'account_settings_users_profile_destroy',
            'account_settings_users_profile_delete',

        ] as $name) {
            $permission7 = Permission::where('name', $name)->first();
            $role7->givePermissionTo($permission7);
        }
    }
}
